branches:
  only:
    - development
    - master

language: rust
sudo: false
addons:
  firefox: latest

cache: cargo

before_cache:
  - ./ci/clear_cache.sh

rust:
  - 1.43.0
  - stable

matrix:
  fast_finish: true

install:
  - rustup component add rustfmt
  - rustup component add clippy
  - rustup install stable
  - rustup target add wasm32-unknown-unknown

script:
  - ./ci/run_checks.sh